### ISSUE TITLE
Practica de RA con Objetos 3D

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-josue#2]
[OBJETO 3D-EQUIPO-JOSUE.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-josue/files/6628796/OBJETO.3D-EQUIPO-JOSUE.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
