### ISSUE TITLE
Objeto 3D GPS

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-josue#3]
[OBJETO 3D-EQUIPO-JOSUE.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-josue/files/6762155/OBJETO.3D-EQUIPO-JOSUE.pdf)

**Comment by Danae953** [comment]
Calificación 72

**Comment by Danae953** [comment]
Calificación 18

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
